name: circular_color_picker
description: Simple, optimized and usefull package to add HSV color picker to your project.
version: 1.0.0
repository: https://github.com/Korpyc/circular_color_picker

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:
